image: python:latest

generaltester:
  script:
  - pip3 install python-Levenshtein
  - apt-get update
  - apt-get -y install curl wget apache2 shellcheck
  - wget -O shfmt https://github.com/mvdan/sh/releases/download/v3.1.2/shfmt_v3.1.2_linux_amd64
  - chmod +x ./shfmt
  - cat /etc/os-release
  - bash grade.sh
  timeout: 2 hours 30 minutes
  artifacts:
    when: always
    paths:
      - results.txt
    expire_in: 1 month
